use_frameworks!

target 'FNVoiceManagerPod_Example' do
# pod 'FNVoiceManagerPod', :path => '../'
  pod 'FNVoiceManagerPod',  :git => 'https://github.com/jiaruijj/VoiceManager.git'
  target 'FNVoiceManagerPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
